### ISSUE TITLE
Add texture to ARSurface shader

### ISSUE THREAD

**Issue by JackM36** [jonas-johansson/ARCoreUtils#2]
Hello,

I am using your shader for shadows, however I would like to show a visualization of the tracked ground like the default one in ARCore. So my question is how would I add texture to the shader (with transparency)?

**Comment by jonas-johansson** [comment]
Hi,

For that to work you need to do two things: generate uv coordinates for the generated mesh AND modify the shader to make it sample from a texture.

To learn more about this I'd suggest reading up on uv coordinates:
https://docs.unity3d.com/ScriptReference/Mesh-uv.html

As for getting the shader to sample from a texture, I'd recommend reading up on how Unity's shaders and materials work:
https://docs.unity3d.com/Manual/Shaders.html

Best of luck
