### ISSUE TITLE
Does not compile with the latest non-beta ARCore

### ISSUE THREAD

**Issue by IcyCheetah358** [jonas-johansson/ARCoreUtils#3]
Assets/Neuston/ARCoreUtils/ARSurface.cs(44,18): error CS0117: `GoogleARCore.Frame' does not contain a definition for `TrackingState'

Assets/Neuston/ARCoreUtils/ARSurfaceManager.cs(16,13): error CS0117: `GoogleARCore.Frame' does not contain a definition for `TrackingState'

Assets/Neuston/ARCoreUtils/ARSurfaceManager.cs(21,9): error CS0117: `GoogleARCore.Frame' does not contain a definition for `GetPlanes'

Assertion failed: Assertion failed on expression: 'm_CurrentEntriesPtr != NULL && m_IsGettingEntries'
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

Assertion failed: Assertion failed on expression: 'm_CurrentEntriesPtr != NULL && m_IsGettingEntries'
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

**Comment by jonas-johansson** [comment]
Yeah, I haven't had time to adjust ARCoreUtils to the new APIs. If anyone wants to fix it and submit a pull request go ahead. I'll see if I have time to patch it up at some point.

Cheers

**Comment by eisenbruch** [comment]
I will do this shortly :) Already have the necessary fixes in a couple of projects.

**Comment by eisenbruch** [comment]
Just submitted the pull request. My first one of these...I hope I did it correctly. If I didn't, I am looking to learn and improve.

**Comment by jonas-johansson** [comment]
With the friendly upgrade from eisenbruch this issue should be resolved.
