### ISSUE TITLE
Problems in Frame.cs after updating google AR core.

### ISSUE THREAD

**Issue by bpca17** [jonas-johansson/ARCoreUtils#5]
Hi,

It appears you have not updated your scripts based google AR core latest update.
I am getting few errors.
Please help.

Errors:
Assets/Neuston/ARCoreUtils/ARSurface.cs(44,18): error CS0117: `GoogleARCore.Frame' does not contain a definition for `TrackingState'

Assets/Neuston/ARCoreUtils/ARSurfaceManager.cs(16,13): error CS0117: `GoogleARCore.Frame' does not contain a definition for `TrackingState'

Assets/Neuston/ARCoreUtils/ARSurfaceManager.cs(21,9): error CS0117: `GoogleARCore.Frame' does not contain a definition for `GetPlanes'

Thanks,
Bhanu.

**Comment by jonas-johansson** [comment]
Hi,

I received a pull request yesterday that I accepted. I haven't had time to test it yet but I would have assumed that the ARCore 1.1 + ARCoreUtils would work. Do you have the latest version of ARCoreUtils?

**Comment by bpca17** [comment]
Yes, I have Updated and now I am testing.
Everything seems fine.
Awesome plugin.

Thanks,
Bhanu.

**Comment by jonas-johansson** [comment]
Glad to hear that! :)
