### ISSUE TITLE
Shadows Disappearing at distance

### ISSUE THREAD

**Issue by joejyong** [jonas-johansson/ARCoreUtils#7]
Hey there, 

Been using your tool for the last couple of months and it's been super helpful. 
I've noticed over the last week or two since updating to V1.1 that shadows are seeming to pop out and disappear at a distance, usually anything over about 2-3 meters. 

I've already spent time tweaking around in quality controls and set shadow render distances higher. Shadows still cast onto all other objects with any standard kind of shader on them, it seems to only be when happening with this ARSurface shader. 

Any chance you might have an idea on what could be the issue here? 

Many thanks in advance

**Comment by jonas-johansson** [comment]
Happy to hear that you find it useful.

I'm aware of one "glitch" where the shadows stop rendering when tilting the
camera up away from the objects on the ground, there is a pop where the
shadows stop being rendered.

But what you're describing is new to me. Have you tried the demo scene in
the repository? Do you get it there?

Cheers

**Comment by joejyong** [comment]
Hey thanks for the quick reply. 

Yeah I also building the demo scene straight out of your repository and got the same issue. I also reimported all of your files into my own project again to make sure they were all identical but it still seems to persist.

https://youtu.be/w31g-Nljmq4

Here's a link to a short clip showing you the kind of behaviour that's happening. There are no edits made to your shader, I have tried on a samsung s8 and pixel2 xl and both seem to have the same issue. 

Thanks again

**Comment by jonas-johansson** [comment]
Yeah, that definitely looks like the issue I've been seeing.

I ran some tests yesterday to see if the ARSurface mesh was being culled out (and not rendered) but it was still rendered fine. The shadows of the objects in the scene, however, stop being rendered in certain situations.

Because of those findings I believe it to be a bug _outside_ of ARCoreUtils - either in Unity or with how ARCore sets up the camera frustum for shadow rendering. Therefore I'll close the issue here, but I could of course be wrong and I'll keep an eye on it. Let me know if you find something as well.

**Comment by joejyong** [comment]
Okay I'll let you know if I find a solution on my end in future. 

Thanks for your help

**Comment by jonas-johansson** [comment]
Hi again,

I had another look at it. In my test case this issue appears when having Shadow Projection set to Close Fit. Setting it to Stable Fit and pulling Shadow Distance down to 15 fixes the shadow popping in and out _but_ the shadows look worse because Unity doesn't support Shadow Cascades on mobile.

> Cascades settings don't affect shadow quality on mobile. Try reducing shadow distance. https://forum.unity.com/threads/unity-5-mobile-shadow-quality-settings.310269/

So for now, until Unity supports higher quality shadows on mobile, you'll probably have to live with Stable Fit and a low Shadow Distance.

**Comment by joejyong** [comment]
Hey,
Yeah I had played around with Stable fit, but the lower quality wasn't suitable for what I'm working on.
I managed to get the results I need by replacing the ARSurface shader another that I will post below for reference. 

The downside is that it doesn't have the object culling like your original shader, so it may not be a suitable fix for others. 
However, for my use I don't necessarily need Object culling on the material anyway, so plugging this shader into your ARSurface prefab has done the trick and allowed me to keep my original high res shadow settings with all shadow popping issues resolved. 

Thanks for your help again, appreciate it.

Shader "Custom/TransparentShadowCollector"
{
    Properties
    {
        _ShadowIntensity ("Shadow Intensity", Range (0, 1)) = 0.6
    }
 
 
    SubShader
    {
 
        Tags {"Queue"="AlphaTest" }
 
        Pass
        {
            Tags {"LightMode" = "ForwardBase" }
            Cull Back
            Blend SrcAlpha OneMinusSrcAlpha
            CGPROGRAM
            #pragma vertex vert
            #pragma fragment frag
            #pragma multi_compile_fwdbase
 
            #include "UnityCG.cginc"
            #include "AutoLight.cginc"
            uniform float _ShadowIntensity;
 
            struct v2f
            {
                float4 pos : SV_POSITION;
                LIGHTING_COORDS(0,1)
            };
            v2f vert(appdata_base v)
            {
                v2f o;
                o.pos = mul (UNITY_MATRIX_MVP, v.vertex);
                TRANSFER_VERTEX_TO_FRAGMENT(o);
               
                return o;
            }
            fixed4 frag(v2f i) : COLOR
            {
                float attenuation = LIGHT_ATTENUATION(i);
                return fixed4(0,0,0,(1-attenuation)*_ShadowIntensity);
            }
            ENDCG
        }
 
    }
    Fallback "VertexLit"
}

**Comment by jonas-johansson** [comment]
Interesting, thanks for sharing!

**Comment by eisenbruch** [comment]
Ended up just using this in one one of my projects. Thanks @joejyong

**Comment by junhochoi-gamedev** [comment]
I was able to fix this issue by adding the LightMode pass tag to the latest ARSurface shader.
(Unity 2018.1.1f1, ARCore 1.3.0)

```shaderlab
SubShader
{
	Pass
	{
		Tags { "LightMode" = "ForwardBase" }

		...
	}
}
```

**Comment by jonas-johansson** [comment]
That's great to hear!
